-- Paso 1: equipos, recepción y fotos. Ejecutar en Supabase → SQL Editor (Run).
-- Ajusta las políticas cuando añadas autenticación.

create table if not exists public.equipos (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  tamano_pantalla text,
  procesador text,
  touch boolean not null default false,
  video text,
  ram text,
  ssd text,
  hdd text,
  etapa text not null default 'pendiente_recepcion',
  created_at timestamptz not null default now()
);

create table if not exists public.recepciones (
  id bigint generated by default as identity primary key,
  equipo_id bigint not null references public.equipos (id) on delete cascade,
  estado_fisico text not null,
  comentarios text,
  created_at timestamptz not null default now(),
  unique (equipo_id)
);

create table if not exists public.recepcion_fotos (
  id bigint generated by default as identity primary key,
  recepcion_id bigint not null references public.recepciones (id) on delete cascade,
  storage_path text not null,
  orden int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_equipos_etapa on public.equipos (etapa);
create index if not exists idx_equipos_created on public.equipos (created_at desc);
create index if not exists idx_recepciones_equipo on public.recepciones (equipo_id);

alter table public.equipos enable row level security;
alter table public.recepciones enable row level security;
alter table public.recepcion_fotos enable row level security;

drop policy if exists "equipos_anon_all" on public.equipos;
create policy "equipos_anon_all" on public.equipos
  for all to anon using (true) with check (true);

drop policy if exists "recepciones_anon_all" on public.recepciones;
create policy "recepciones_anon_all" on public.recepciones
  for all to anon using (true) with check (true);

drop policy if exists "recepcion_fotos_anon_all" on public.recepcion_fotos;
create policy "recepcion_fotos_anon_all" on public.recepcion_fotos
  for all to anon using (true) with check (true);

drop policy if exists "equipos_auth_all" on public.equipos;
create policy "equipos_auth_all" on public.equipos
  for all to authenticated using (true) with check (true);

drop policy if exists "recepciones_auth_all" on public.recepciones;
create policy "recepciones_auth_all" on public.recepciones
  for all to authenticated using (true) with check (true);

drop policy if exists "recepcion_fotos_auth_all" on public.recepcion_fotos;
create policy "recepcion_fotos_auth_all" on public.recepcion_fotos
  for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('recepcion-fotos', 'recepcion-fotos', true)
on conflict (id) do nothing;

drop policy if exists "recepcion_fotos_storage_select" on storage.objects;
create policy "recepcion_fotos_storage_select" on storage.objects
  for select to anon using (bucket_id = 'recepcion-fotos');

drop policy if exists "recepcion_fotos_storage_insert" on storage.objects;
create policy "recepcion_fotos_storage_insert" on storage.objects
  for insert to anon with check (bucket_id = 'recepcion-fotos');

drop policy if exists "recepcion_fotos_storage_select_auth" on storage.objects;
create policy "recepcion_fotos_storage_select_auth" on storage.objects
  for select to authenticated using (bucket_id = 'recepcion-fotos');

drop policy if exists "recepcion_fotos_storage_insert_auth" on storage.objects;
create policy "recepcion_fotos_storage_insert_auth" on storage.objects
  for insert to authenticated with check (bucket_id = 'recepcion-fotos');
